# Generated by Django 3.0.3 on 2020-05-05 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Budgetentry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='Paymode',
            field=models.CharField(max_length=250),
        ),
    ]
