# Generated by Django 3.0.3 on 2020-05-06 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Budgetentry', '0002_auto_20200505_2354'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('Paymode', 'Username')},
        ),
    ]
