# Generated by Django 3.0.3 on 2020-05-06 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Budgetentry', '0003_auto_20200507_0056'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='essential',
            unique_together={('Category', 'Username')},
        ),
    ]
